blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/withastro/flue/discussions/new?category=feature-request
    about: Propose and discuss new features, improvements, and RFCs.
